name: Run Shard0 Analysis

on:
  schedule:
   - cron: '0 */2 * * *'  # Запуск каждые пол часа (настраиваем по необходимости)
  workflow_dispatch:  # Вручную запустить, если нужно

jobs:
  shard0:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Shard0 analysis
      run: python main_shard0.py  # Ваш скрипт
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # Получаем ID чата
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Получаем токен из секретов
        CRYPTOCOMPARE_API_KEY: ${{ secrets.CRYPTOCOMPARE_API_KEY }}  # Получаем API ключ
